changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]

  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking

    - title: New Features
      labels:
        - feature
        - enhancement

    - title: Bug Fixes
      labels:
        - bug
        - bugfix
        - fix

    - title: Documentation
      labels:
        - documentation
        - docs

    - title: Performance
      labels:
        - performance
        - perf

    - title: Other Changes
      labels:
        - "*"
